### ISSUE TITLE
Can't install last version of Wagon gem. Only v.1.5.8 seems available

### ISSUE THREAD

**Issue by gcolson** [locomotivecms/wagon#396]
Hi,

I'm struggling at the very beggining of the "Quick Start" Guide at https://doc.locomotivecms.com/docs, as I simply cannot install the latest version of wagon (3.0.5 at the time i'm writing this).
I'm using Ubuntu 20.04. I first installed ruby following this guide : https://gorails.com/setup/ubuntu/20.04

```
> ruby -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
```

Then I try to install wagon using `gem install locomotivecms_wagon`
but it installs the 1.5.8 version.

So I try forcing the latest version using `gem install locomotivecms_wagon -v 3.0.5` but i got the following error :

```
ERROR: While executing gem ... (NoMethodError)
undefined method `request' for nil:NilClass
```

Can somebody help me here ? I really don't understand what's going on. I never experienced such issues with other standalone gem installations.

Thanks a lot,

Grégoire

**Comment by gcolson** [comment]
Seems to be working using ruby 2.7.2. Could be usefull to specify not to use a ruby version < 3.0 in the docs. Would have save me a few hours of work ;)

**Comment by greyskin** [comment]
Yeah I feel you - I've had countless issues getting Wagon installed. Same operating system, same setup, will get a completely different error. Once you've got it working you'll be away laughing but it really is a barrier - one that I think few make it past.
