### ISSUE TITLE
exec wagon serve error: Rails not recognizing Wagon bin file?

### ISSUE THREAD

**Issue by amadaneus** [locomotivecms/wagon#342]
Hey everyone, I could use some help: I'm trying out LocomotiveCMS on Windows 10 and I'm working with Rails 5.1.4/Ruby 2.3.3. I have the most recent version of LocomotiveCMS( locomotivecms-liquid (4.0.0) locomotivecms-solid (4.0.1) locomotivecms_coal(1.3.0) , locomotivecms_common (0.2.0), locomotivecms_steam (1.2.1) , locomotivecms_wagon (2.2.0))

I'm following the QuickStart guide. After running the gem install, init, and bundle install commands from my project directory, I run into the following issue below. Prior to this error I had issues related to the redcloth_scan file showing up missing(fixed using this [method:](https://github.com/locomotivecms/engine/issues/1042))

I'm not sure how to read this error: my interpretation is that Rails can't "see" the wagon file in the bin folder.

Can someone tell me what the actual error is and how to fix or work around it? I'd really like to use Locomotive.

> C:\Users\D\WebDev\Client\ClientTest1>bundle exec wagon serve -v
> C:/RailsInstaller/Ruby2.3.3/bin/wagon: No such file or directory - which convert
> 
> # Error description:
> undefined method `strip' for nil:NilClass
> 
> # Backtrace:
> 
>         C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/locomotivecms_steam-1.2.1/lib/locomotive/steam/initializers/dragonfly.rb:33:in `find_imagemagick_commands'
>         C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/locomotivecms_steam-1.2.1/lib/locomotive/steam/initializers/dragonfly.rb:11:in `run'
>         C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/locomotivecms_steam-1.2.1/lib/locomotive/steam/initializers/dragonfly.rb:56:in `<top (required)>'
>         C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/locomotivecms_steam-1.2.1/lib/locomotive/steam/initializers.rb:3:in `require_relative'
>         C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/locomotivecms_steam-1.2.1/lib/locomotive/steam/initializers.rb:3:in `<top (required)>'
>         C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/locomotivecms_steam-1.2.1/lib/locomotive/steam.rb:42:in `require_relative'
>         C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/locomotivecms_steam-1.2.1/lib/locomotive/steam.rb:42:in `configure'
>         C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.2.0/lib/locomotive/wagon/commands/serve_command.rb:77:in `require_steam'
>         C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.2.0/lib/locomotive/wagon/commands/serve_command.rb:25:in `start'
>         C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.2.0/lib/locomotive/wagon/commands/serve_command.rb:13:in `start'
>         C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.2.0/lib/locomotive/wagon.rb:39:in `serve'
>         C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.2.0/lib/locomotive/wagon/cli.rb:286:in `serve'
>         C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
>         C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
>         C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
>         C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
>         C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.2.0/bin/wagon:12:in `<top (required)>'
>         C:/RailsInstaller/Ruby2.3.3/bin/wagon:22:in `load'
>         C:/RailsInstaller/Ruby2.3.3/bin/wagon:22:in `<main>'
>

**Comment by manuchap** [comment]
`convert` is the executable command installed with **ImageMagick** which is a third party library used by wagon/engine to crop/resize images in the backend or on the fly in your markup as explained [here](https://locomotive-v3.readme.io/v3.3/docs/filters#section-resize).
You need to install it following [this tutorial](http://imagemagick.sourceforge.net/http/www/windows.html).
There needn't (shouldn't) be a bin folder in your wagon sites.

**Comment by greyskin** [comment]
I'm getting exactly the same error and installing ImageMagick didn't change a thing...

By the way, the bin folder it is looking for isn't in the site - it's in the Ruby installation folder.

**Comment by greyskin** [comment]
Right, I'm a bit of newbie so anyone feel free to chip in if the following is bad advice (altering actual files) - I was desperate so willing to give anything a crack.

This post (https://gist.github.com/istickz/9475935 - in Russian) contained a solution.

Find the dragonfly.rb file (for my installation it was under /lib/locomotive/steam/initializers/dragonfly.db

Change the following:
```
convert   = ENV['IMAGE_MAGICK_CONVERT'] || `which convert`.strip.presence || '/usr/local/bin/convert'
```

to:
```
convert   = ENV['IMAGE_MAGICK_CONVERT'] || `where convert`.strip.presence
```

Additionally, change the following:

```
identify  = ENV['IMAGE_MAGICK_IDENTIFY'] || `which identify`.strip.presence || '/usr/local/bin/identify'
```

to:

```
identify  = ENV['IMAGE_MAGICK_IDENTIFY'] || `where identify`.strip.presence
```

This got me past the ImageMagick errors and of course another completely new error is thrown. Getting RoR + Locomotive to work has so far taken me AGES... on we go.
